version: '3.9'

services:
  frontend:
    image: giodev68/cv-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    image: giodev68/cv-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
